name: python-exercises
channels:
  - conda-forge
dependencies:
  - python=3.10.19
  - pandas=2.3.3
  - doit=0.36
  - pytest=8.4.2
  - flake8
  - scipy=1.15.3
  - statsmodels=0.14
  - plotly=6.3.0
  - python-dotenv=1.1.0
  - scikit-learn=1.7.2
  - psycopg2=2.9.10
  - jupyter=1.1.1
  - pyyaml=6.0.2
  - tabulate=0.9.0
